services:
  mysql:
    image: mysql:9.0.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nodejs
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: caching_sha2_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql-data:
